config/routes.rb
QuoteBuilder::Application.routes.draw do
  get "home/index"

  get "home/about"

  devise_for :users

  namespace :api do
    resources :decriptions
    resources :authors
    resources :quotes
  end

  root :to => "home#index"
  match '*path' => "home#index"

end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :first_name, :last_name
end

app/models/decription.rb
class Decription < ActiveRecord::Base
  attr_accessible :quote_id, :text, :user_id
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  attr_accessible :author_id, :quote
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/api/authors_controller.rb
class Api::AuthorsController < ApplicationController
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
    render json: @authors
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])
    render json: @author
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new
    render json: @author
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    render json: @author
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    render json: @author
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    render json: @author
  end
end

app/controllers/api/decriptions_controller.rb
class Api::DecriptionsController < ApplicationController
  # GET /decriptions
  # GET /decriptions.json
  def index
    @decriptions = Decription.all

    render json: @descriptions
  end

  # GET /decriptions/1
  # GET /decriptions/1.json
  def show
    @decription = Decription.find(params[:id])

    render json: @description
  end

  # GET /decriptions/new
  # GET /decriptions/new.json
  def new
    @decription = Decription.new

    render json: @description
  end

  # GET /decriptions/1/edit
  def edit
    @decription = Decription.find(params[:id])
  end

  # POST /decriptions
  # POST /decriptions.json
  def create
    @decription = Decription.new(params[:decription])

    render json: @description
  end

  # PUT /decriptions/1
  # PUT /decriptions/1.json
  def update
    @decription = Decription.find(params[:id])

    render json: @description
  end

  # DELETE /decriptions/1
  # DELETE /decriptions/1.json
  def destroy
    @decription = Decription.find(params[:id])
    @decription.destroy

    render json: @description

  end
end

app/controllers/api/quotes_controller.rb
class Api::QuotesController < ApplicationController
  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all

    render json: @quotes
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
    @quote = Quote.find(params[:id])

    render json: @quote
  end

  # GET /quotes/new
  # GET /quotes/new.json
  def new
    @quote = Quote.new

    render json: @quote
  end

  # GET /quotes/1/edit
  def edit
    @quote = Quote.find(params[:id])
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(params[:quote])
    render json: @quote
  end

  # PUT /quotes/1
  # PUT /quotes/1.json
  def update
    @quote = Quote.find(params[:id])

    render json: @quote
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote = Quote.find(params[:id])
    @quote.destroy

      render json: @quote
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/decriptions_helper.rb
module DecriptionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/authors/_form.html.haml
= form_for @author do |f|
  - if @author.errors.any?
    #error_explanation
      %h2= "#{pluralize(@author.errors.count, "error")} prohibited this author from being saved:"
      %ul
        - @author.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .actions
    = f.submit 'Save'

app/views/authors/edit.html.haml
%h1 Editing author

= render 'form'

= link_to 'Show', @author
\|
= link_to 'Back', authors_path

app/views/authors/index.html.haml
%h1 Listing authors

%table
  %tr
    %th First name
    %th Last name
    %th
    %th
    %th

  - @authors.each do |author|
    %tr
      %td= author.first_name
      %td= author.last_name
      %td= link_to 'Show', author
      %td= link_to 'Edit', edit_author_path(author)
      %td= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Author', new_author_path

app/views/authors/new.html.haml
%h1 New author

= render 'form'

= link_to 'Back', authors_path

app/views/authors/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @author.first_name
%p
  %b Last name:
  = @author.last_name

= link_to 'Edit', edit_author_path(@author)
\|
= link_to 'Back', authors_path

app/views/decriptions/_form.html.haml
= form_for @decription do |f|
  - if @decription.errors.any?
    #error_explanation
      %h2= "#{pluralize(@decription.errors.count, "error")} prohibited this decription from being saved:"
      %ul
        - @decription.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :quote_id
    = f.number_field :quote_id
  .field
    = f.label :text
    = f.text_area :text
  .actions
    = f.submit 'Save'

app/views/decriptions/edit.html.haml
%h1 Editing decription

= render 'form'

= link_to 'Show', @decription
\|
= link_to 'Back', decriptions_path

app/views/decriptions/index.html.haml
%h1 Listing decriptions

%table
  %tr
    %th User
    %th Quote
    %th Text
    %th
    %th
    %th

  - @decriptions.each do |decription|
    %tr
      %td= decription.user_id
      %td= decription.quote_id
      %td= decription.text
      %td= link_to 'Show', decription
      %td= link_to 'Edit', edit_decription_path(decription)
      %td= link_to 'Destroy', decription, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Decription', new_decription_path

app/views/decriptions/new.html.haml
%h1 New decription

= render 'form'

= link_to 'Back', decriptions_path

app/views/decriptions/show.html.haml
%p#notice= notice

%p
  %b User:
  = @decription.user_id
%p
  %b Quote:
  = @decription.quote_id
%p
  %b Text:
  = @decription.text

= link_to 'Edit', edit_decription_path(@decription)
\|
= link_to 'Back', decriptions_path

app/views/home/about.html.haml
%h1 Home#about
%p Find me in app/views/home/about.html.haml

app/views/home/index.html.haml
#content

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuoteBuilder</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/quotes/_form.html.haml
= form_for @quote do |f|
  - if @quote.errors.any?
    #error_explanation
      %h2= "#{pluralize(@quote.errors.count, "error")} prohibited this quote from being saved:"
      %ul
        - @quote.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :quote
    = f.text_area :quote
  .field
    = f.label :author_id
    = f.number_field :author_id
  .actions
    = f.submit 'Save'

app/views/quotes/edit.html.haml
%h1 Editing quote

= render 'form'

= link_to 'Show', @quote
\|
= link_to 'Back', quotes_path

app/views/quotes/index.html.haml
%h1 Listing quotes

%table
  %tr
    %th Quote
    %th Author
    %th
    %th
    %th

  - @quotes.each do |quote|
    %tr
      %td= quote.quote
      %td= quote.author_id
      %td= link_to 'Show', quote
      %td= link_to 'Edit', edit_quote_path(quote)
      %td= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Quote', new_quote_path

app/views/quotes/new.html.haml
%h1 New quote

= render 'form'

= link_to 'Back', quotes_path

app/views/quotes/show.html.haml
%p#notice= notice

%p
  %b Quote:
  = @quote.quote
%p
  %b Author:
  = @quote.author_id

= link_to 'Edit', edit_quote_path(@quote)
\|
= link_to 'Back', quotes_path